version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/test
    overwrite: yes
permissions:
  - object: /home/ec2-user/test
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 300
      runas: root