name: deploy to S3

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: cjgbucket
  CODE_DEPLOY_APPLICATION_NAME: cjg-react
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: react

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.9.0]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 프로젝트 빌드
      - name: Build next app
        run: npm run build

      - name: Make zip file
        run: zip -qq -r ./chagok.zip . -x "node_modules/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./chagok.zip s3://$S3_BUCKET_NAME/chagok.zip          


